/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

/**
 *
 * @author rapha
 */
public class TelaTanque extends javax.swing.JFrame {

    /**
     * Creates new form TelaTanque
     */
    public TelaTanque() {
        initComponents();
      
        panTanque.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEncher = new javax.swing.JButton();
        panTanque = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEncher.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEncher.setText("Por favor, encher o tanque!");
        btnEncher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncherActionPerformed(evt);
            }
        });
        getContentPane().add(btnEncher, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tanque2.gif"))); // NOI18N

        javax.swing.GroupLayout panTanqueLayout = new javax.swing.GroupLayout(panTanque);
        panTanque.setLayout(panTanqueLayout);
        panTanqueLayout.setHorizontalGroup(
            panTanqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTanqueLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(31, 31, 31))
        );
        panTanqueLayout.setVerticalGroup(
            panTanqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTanqueLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(panTanque, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 470, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncherActionPerformed
        // TODO add your handling code here:
      
        panTanque.setVisible(true);
    }//GEN-LAST:event_btnEncherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTanque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEncher;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panTanque;
    // End of variables declaration//GEN-END:variables
}
